"""
Audit event type definitions and AuditEvent dataclass.

Defines standardized event categories:
- TASK_INVOCATION: Task invocation lifecycle events
- PHASE: TDD phase execution events
- SUBAGENT_STOP: Subagent termination events
- COMMIT: Git commit events
- AGENT_USAGE: Per-message token-usage observations from Claude transcripts

``EventType`` and ``AuditEvent`` are re-exported from ``des.domain.audit_events``
(the SSOT, moved there by the techdebt drain of
``application-layer-imports-adapters-directly`` -- both are pure value objects
with zero I/O, so the application layer can depend on their domain-layer home
without crossing the hexagonal ports/adapters boundary). Kept importable from
here so every existing caller of this adapter module stays unbroken.
"""

from dataclasses import dataclass
from typing import Any

from des.domain.audit_events import AuditEvent, EventType


__all__ = ["AgentUsageObservedEvent", "AuditEvent", "EventType"]


@dataclass(frozen=True)
class AgentUsageObservedEvent:
    """One token-usage observation extracted from a Claude transcript message.

    Per-message granularity (D5): one event per assistant message that
    carries a valid `message.usage` block in the Anthropic transcript JSONL
    format. Aggregation across messages is deferred to the analytics layer.

    Attributes:
        agent_name: The Claude Code sub-agent type that produced the message
            (e.g., "researcher", "software-crafter").
        model: The Anthropic model identifier from the transcript message
            (e.g., "claude-opus-4-7-20251101").
        timestamp: ISO 8601 timestamp from the transcript entry.
        input_tokens: Fresh input tokens from message.usage.input_tokens.
        cache_creation_input_tokens: Tokens written to the prompt cache.
        cache_read_input_tokens: Tokens served from the prompt cache.
        output_tokens: Tokens generated by the model.
        feature_id: Optional feature identifier for traceability.
        wave: Optional wave name (DISCOVER..DELIVER) for traceability.
    """

    agent_name: str
    model: str
    timestamp: str
    input_tokens: int
    cache_creation_input_tokens: int
    cache_read_input_tokens: int
    output_tokens: int
    feature_id: str | None = None
    wave: str | None = None

    def to_audit_data(self) -> dict[str, Any]:
        """Render the event as the `data` payload for the port-level AuditEvent.

        The port-level AuditEvent (in audit_log_writer.py) carries an
        `event_type` plus a `data` dict that JsonlAuditLogWriter merges into
        the JSONL line. This method produces that data dict, excluding
        None-valued optional fields for clean output.
        """
        payload: dict[str, Any] = {
            "agent_name": self.agent_name,
            "model": self.model,
            "input_tokens": self.input_tokens,
            "cache_creation_input_tokens": self.cache_creation_input_tokens,
            "cache_read_input_tokens": self.cache_read_input_tokens,
            "output_tokens": self.output_tokens,
        }
        if self.feature_id is not None:
            payload["feature_id"] = self.feature_id
        if self.wave is not None:
            payload["wave"] = self.wave
        return payload
