"""
Audit event type definitions and AuditEvent dataclass.

Defines standardized event categories:
- TASK_INVOCATION: Task invocation lifecycle events
- PHASE: TDD phase execution events
- SUBAGENT_STOP: Subagent termination events
- COMMIT: Git commit events
- AGENT_USAGE: Per-message token-usage observations from Claude transcripts
"""

from dataclasses import asdict, dataclass
from enum import Enum
from typing import Any


class EventType(Enum):
    """Audit event type categories."""

    # TASK_INVOCATION events
    TASK_INVOCATION_STARTED = "TASK_INVOCATION_STARTED"
    TASK_INVOCATION_VALIDATED = "TASK_INVOCATION_VALIDATED"
    TASK_INVOCATION_REJECTED = "TASK_INVOCATION_REJECTED"

    # PHASE events
    PHASE_STARTED = "PHASE_STARTED"
    PHASE_EXECUTED = "PHASE_EXECUTED"
    PHASE_SKIPPED = "PHASE_SKIPPED"
    PHASE_FAILED = "PHASE_FAILED"

    # SUBAGENT_STOP events
    SUBAGENT_STOP_VALIDATION = "SUBAGENT_STOP_VALIDATION"
    SUBAGENT_STOP_FAILURE = "SUBAGENT_STOP_FAILURE"

    # COMMIT events
    COMMIT_SUCCESS = "COMMIT_SUCCESS"
    COMMIT_FAILURE = "COMMIT_FAILURE"

    # VALIDATION events
    VALIDATION_REJECTED = "VALIDATION_REJECTED"

    # HOOK events
    HOOK_PRE_TASK_PASSED = "HOOK_PRE_TASK_PASSED"
    HOOK_PRE_TASK_BLOCKED = "HOOK_PRE_TASK_BLOCKED"
    HOOK_SUBAGENT_STOP_PASSED = "HOOK_SUBAGENT_STOP_PASSED"
    HOOK_SUBAGENT_STOP_FAILED = "HOOK_SUBAGENT_STOP_FAILED"

    # AGENT_USAGE events (L1 token instrumentation)
    AGENT_USAGE_OBSERVED = "AGENT_USAGE_OBSERVED"

    # HEALTH_GATE events (DV-5 — install-freshness dual-emit, KPI-1 sink)
    HEALTH_GATE_INSTALL_FRESHNESS_STALE = "HEALTH_GATE_INSTALL_FRESHNESS_STALE"
    # SYS-4 / AD-27 — shipped config-asset drift (lib/nWave/) dual-emit
    HEALTH_GATE_INSTALL_FRESHNESS_CONFIG_DRIFT = (
        "HEALTH_GATE_INSTALL_FRESHNESS_CONFIG_DRIFT"
    )


@dataclass(frozen=True)
class AgentUsageObservedEvent:
    """One token-usage observation extracted from a Claude transcript message.

    Per-message granularity (D5): one event per assistant message that
    carries a valid `message.usage` block in the Anthropic transcript JSONL
    format. Aggregation across messages is deferred to the analytics layer.

    Attributes:
        agent_name: The Claude Code sub-agent type that produced the message
            (e.g., "researcher", "software-crafter").
        model: The Anthropic model identifier from the transcript message
            (e.g., "claude-opus-4-7-20251101").
        timestamp: ISO 8601 timestamp from the transcript entry.
        input_tokens: Fresh input tokens from message.usage.input_tokens.
        cache_creation_input_tokens: Tokens written to the prompt cache.
        cache_read_input_tokens: Tokens served from the prompt cache.
        output_tokens: Tokens generated by the model.
        feature_id: Optional feature identifier for traceability.
        wave: Optional wave name (DISCOVER..DELIVER) for traceability.
    """

    agent_name: str
    model: str
    timestamp: str
    input_tokens: int
    cache_creation_input_tokens: int
    cache_read_input_tokens: int
    output_tokens: int
    feature_id: str | None = None
    wave: str | None = None

    def to_audit_data(self) -> dict[str, Any]:
        """Render the event as the `data` payload for the port-level AuditEvent.

        The port-level AuditEvent (in audit_log_writer.py) carries an
        `event_type` plus a `data` dict that JsonlAuditLogWriter merges into
        the JSONL line. This method produces that data dict, excluding
        None-valued optional fields for clean output.
        """
        payload: dict[str, Any] = {
            "agent_name": self.agent_name,
            "model": self.model,
            "input_tokens": self.input_tokens,
            "cache_creation_input_tokens": self.cache_creation_input_tokens,
            "cache_read_input_tokens": self.cache_read_input_tokens,
            "output_tokens": self.output_tokens,
        }
        if self.feature_id is not None:
            payload["feature_id"] = self.feature_id
        if self.wave is not None:
            payload["wave"] = self.wave
        return payload


@dataclass
class AuditEvent:
    """Structured audit event with complete execution context."""

    timestamp: str  # ISO 8601 format: YYYY-MM-DDTHH:MM:SS.sssZ
    event: str  # Event type from EventType enum
    feature_name: str | None = None  # Feature name from step file
    step_id: str | None = None  # Step identifier (e.g., "01-02")
    phase_name: str | None = None  # Name of the TDD phase
    status: str | None = None  # Phase status: IN_PROGRESS, EXECUTED, SKIPPED
    outcome: str | None = None  # Success or failure outcome
    duration_minutes: float | None = None  # Duration of phase/event
    reason: str | None = None  # Reason for failure/rejection
    commit_hash: str | None = None  # Git commit hash (for COMMIT events)
    rejection_reason: str | None = None  # Detailed rejection reason
    extra_context: dict[str, Any] | None = None  # Additional contextual data

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization.

        Excludes None values for cleaner JSONL output.
        """
        data = asdict(self)
        # Remove None values
        return {k: v for k, v in data.items() if v is not None}

    @staticmethod
    def from_dict(data: dict[str, Any]) -> "AuditEvent":
        """Create AuditEvent from dictionary.

        Args:
            data: Dictionary with event data

        Returns:
            AuditEvent instance
        """
        return AuditEvent(**data)


def validate_event_type(event_type: str) -> bool:
    """Validate that event type is in allowed categories.

    Args:
        event_type: Event type string to validate

    Returns:
        True if valid, False otherwise
    """
    return any(e.value == event_type for e in EventType)


def get_event_category(event_type: str) -> str:
    """Get event category from event type.

    Args:
        event_type: Event type string (e.g., 'TASK_INVOCATION_STARTED')

    Returns:
        Event category (e.g., 'TASK_INVOCATION')
    """
    if event_type.startswith("TASK_INVOCATION"):
        return "TASK_INVOCATION"
    elif event_type.startswith("PHASE"):
        return "PHASE"
    elif event_type.startswith("SUBAGENT_STOP"):
        return "SUBAGENT_STOP"
    elif event_type.startswith("COMMIT"):
        return "COMMIT"
    elif event_type.startswith("VALIDATION"):
        return "VALIDATION"
    elif event_type.startswith("HOOK"):
        return "HOOK"
    elif event_type.startswith("AGENT_USAGE"):
        return "AGENT_USAGE"
    else:
        return "UNKNOWN"
