"""Acceptance regression for nWave-ai/nwave#32.

The .nwave/.gitignore file MUST exist whenever any runtime code path lazily
creates content under .nwave/. Previously, the SessionStart update check would
write .nwave/des-config.json without ever creating the .gitignore, causing the
generated state to be visible to git.

These scenarios drive the runtime call sites — DES config save, task signal
creation, and skill tracker initialization — through their public APIs and
assert that .nwave/.gitignore is always present afterwards.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from des.adapters.driven.config.des_config import DESConfig
from des.adapters.driven.tracking.jsonl_skill_tracker import JsonlSkillTracker
from des.adapters.drivers.hooks.des_task_signal import create_des_task_signal
from des.domain.skill_load_event import SkillLoadEvent


if TYPE_CHECKING:
    from pathlib import Path


_MARKER = "# Generated by nWave. Do not edit."


def _assert_gitignore(nwave_dir: Path) -> None:
    gitignore = nwave_dir / ".gitignore"
    assert gitignore.exists(), (
        f"Expected {gitignore} to exist after .nwave/ was populated"
    )
    content = gitignore.read_text(encoding="utf-8")
    assert _MARKER in content
    assert "*" in content


def test_des_config_save_update_check_state_creates_gitignore(
    tmp_path: Path,
) -> None:
    """Regression for #32: SessionStart update check must create .gitignore.

    update_check state is machine-scoped, so the save targets the GLOBAL config
    under ~/.nwave/. The .gitignore invariant must hold for that .nwave/ dir.
    """
    global_nwave_dir = tmp_path / "global" / ".nwave"
    global_config_path = global_nwave_dir / "global-config.json"
    config = DESConfig(
        config_path=tmp_path / "proj" / ".nwave" / "des-config.json",
        global_config_path=global_config_path,
    )

    config.save_update_check_state(
        last_checked="2026-04-15T00:00:00Z",
        skipped_versions=[],
    )

    assert global_config_path.exists()
    _assert_gitignore(global_nwave_dir)


def test_create_des_task_signal_creates_gitignore(tmp_path: Path) -> None:
    """Task signal lazily creates .nwave/des/ — must also drop .gitignore."""
    session_dir = tmp_path / ".nwave" / "des"
    task_active_file = session_dir / "des-task-active"

    create_des_task_signal(
        session_dir=session_dir,
        task_active_file=task_active_file,
        step_id="step-1",
        project_id="proj-1",
    )

    assert session_dir.exists()
    _assert_gitignore(tmp_path / ".nwave")


def test_skill_tracker_log_creates_gitignore(tmp_path: Path) -> None:
    """JsonlSkillTracker writes under .nwave/ — must also drop .gitignore."""
    log_path = tmp_path / ".nwave" / "skill-loading-log.jsonl"
    tracker = JsonlSkillTracker(log_path=log_path)

    event = SkillLoadEvent(
        timestamp="2026-04-15T00:00:00Z",
        agent_name="test-agent",
        skill_name="test-skill",
        file_path="/tmp/test-skill/SKILL.md",
        estimated_tokens=42,
    )
    tracker.log_skill_load(event)

    assert log_path.exists()
    _assert_gitignore(tmp_path / ".nwave")
