"""Acceptance test for reverify-slice-commit gate composition (step 01-03).

Step 01-03 -- "Gate composition, success path emits records". Composes the
two real gates (E1 check_slice_at_completeness -- the feature-scoped wrapper
shipped by fix-reverify-e1-via-scoped-wrapper slice-01/02; E2
run_contract_gate) and emits the success ledger record.

Acceptance criteria (feature-delta.md sec.11 step 03, sec.6 no-fabrication):
  1. Both gates' contract results are generated by genuine gate execution,
     never stubbed or faked.
  2. Both gates passing appends a genuine ``SliceCommitVerified`` ledger
     record, HMAC chain intact, exit 0.
  3. A green slice whose suite grew since the commit still reverifies green
     (the R-3 reverify-against-HEAD-suite relaxation).

The fixture is a crafted temp-git repo carrying a real ``@slice-NN``
``.feature`` commit AND a contract-marked test added AFTER it -- so E2's
default ``_mode_run_suite`` actually collects and runs something, and the
slice still reverifies green despite the suite having grown (criterion 3).

No gate stubbing -- invariant I-2 forbids it; stubbing would defeat the
no-fabrication guarantee (feature-delta sec.6).
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from des.adapters.driven.logging.at_completion_ledger import AtCompletionLedger
from des.cli.reverify_slice_commit import main


pytestmark = pytest.mark.acceptance

_FEATURE_ID = "fix-carpaccio-reverify-orphaned-slice"

# A pytest.ini for the temp repo so E2's whole-tree
# `pytest -m "unit or integration or acceptance"` collects -- under
# --strict-markers -- only the contract-marked test crafted below.
_TEMP_PYTEST_INI = """\
[pytest]
markers =
    unit: Unit tests
    integration: Integration tests
    acceptance: Acceptance tests
"""

# A green slice .feature file carrying the @slice-NN + @feature-{id} tags
# E1 (now the feature-scoped check_slice_at_completeness wrapper, post
# fix-reverify-e1-via-scoped-wrapper slice-02) walks for.
_SLICE_FEATURE = """\
@feature-fix-carpaccio-reverify-orphaned-slice @slice-01
Feature: orphaned slice recovery walking skeleton

  Scenario: the slice ships its acceptance criterion
    Given a committed slice
    When the reverify gate runs
    Then the slice is certified green
"""

# A genuinely-passing contract-marked test -- E2 runs it for real.
_CONTRACT_TEST_GREEN = """\
import pytest


@pytest.mark.acceptance
def test_slice_contract_holds():
    assert 1 + 1 == 2
"""

# A genuinely-FAILING contract-marked test -- E2 runs it and goes red.
_CONTRACT_TEST_RED = """\
import pytest


@pytest.mark.acceptance
def test_slice_contract_breaks():
    assert 1 + 1 == 3
"""


def _git(repo: Path, *args: str) -> str:
    """Run a git command in ``repo`` and return stdout."""
    return subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True
    ).stdout


def _init_repo(repo: Path) -> None:
    """Initialise a git repo with deterministic identity."""
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "t@t"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=repo, check=True)


def _commit(repo: Path, message: str) -> str:
    """Stage everything and commit with ``message``; return the commit SHA."""
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", message], cwd=repo, check=True)
    return _git(repo, "rev-parse", "HEAD").strip()


def _argv(repo: Path, slice_id: str, commit: str) -> list[str]:
    return [
        "--repo",
        str(repo),
        "--feature-id",
        _FEATURE_ID,
        "--slice-id",
        slice_id,
        "--commit",
        commit,
    ]


@pytest.fixture
def orphaned_green_slice_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo with a buried green slice + a later contract test.

    History (oldest -> newest):
      1. base commit (pytest.ini so the contract suite is collectable).
      2. SLICE COMMIT -- carries the @slice-01 .feature file + ``Slice-Id``
         trailer. This is the buried slice being reverified.
      3. a later commit that ADDS a contract-marked test -- the suite has
         grown since the slice commit (exercises criterion 3 / R-3).

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # 1. base commit -- the temp repo's own pytest config.
    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    # 2. the slice commit -- the @slice-01 .feature AT lives here.
    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    (features / "slice_01.feature").write_text(_SLICE_FEATURE, encoding="utf-8")
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    # 3. a LATER commit grows the contract suite (criterion 3 / R-3).
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    _commit(repo, "test: add contract test after the slice commit\n")

    return repo, slice_sha


def test_both_gates_pass_appends_genuine_slice_commit_verified_exit_0(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criteria 1+2+3: both real gates pass -> SliceCommitVerified, exit 0.

    The slice commit carries its @slice-01 .feature file (E1 passes against
    the working tree) and the contract suite -- grown since the commit --
    runs genuinely green (E2 passes). The success path appends a real
    ``SliceCommitVerified`` ledger record through ``append_gate_event``;
    the HMAC chain reads back intact under the M7 fail-closed contract.
    """
    repo, slice_sha = orphaned_green_slice_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"

    # Criterion 2: a genuine SliceCommitVerified record was appended, and the
    # whole chain reads back intact under M7 (no LedgerIntegrityViolation).
    records_after = ledger.read_records()
    assert len(records_after) > records_before
    verified = ledger.verified_slices()
    assert "slice-01" in verified
    appended = [r for r in records_after if r["event"] == "SliceCommitVerified"]
    assert any(r["slice_id"] == "slice-01" for r in appended)


def test_slice_commit_verified_record_is_origin_blind(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The reverify-minted record is shape-identical to a U2-minted one.

    feature-delta sec.2 second grounding finding + constraint 4: the
    ``SliceCommitVerified`` record carries no commit SHA and no origin
    field, so ``verified_slices()`` cannot tell a reverify-minted record
    from a U2-minted one -- M8 keeps working.
    """
    repo, slice_sha = orphaned_green_slice_repo

    exit_code = main(_argv(repo, "slice-01", slice_sha))
    assert exit_code == 0
    capsys.readouterr()

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    verified_records = [
        r for r in ledger.read_records() if r["event"] == "SliceCommitVerified"
    ]
    assert verified_records
    record = verified_records[0]
    # Origin-blind: no SHA, no origin marker on the M8-visible record.
    assert slice_sha not in json.dumps(record)
    assert "origin" not in record


@pytest.fixture
def e1_failing_slice_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo whose slice commit fails to carry ALL its `.feature` ATs.

    Step 01-05 NOTE: P4 (in-commit AT presence) subsumes the original shape of
    this fixture -- a commit carrying ZERO `@slice-01` `.feature` files is now
    refused at P4, before E1 ever runs, so it can no longer reach the E1
    gate-fail path. This fixture is rebuilt to exercise the genuine E1
    contract WHILE satisfying P4: the slice commit DOES carry one `@slice-01`
    `.feature` (P4 passes), but the working tree gains a SECOND `@slice-01`
    `.feature` that the commit never carried and that was not tracked before
    -- the RCA Branch-A defect E1 (`check_slice_at_completeness`, the
    feature-scoped wrapper post fix-reverify-e1-via-scoped-wrapper) reports
    as `incomplete`, exiting non-zero. The behavioral assertion
    (E1 fails -> `SliceReverifyBlocked` naming E1) is unchanged.

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    # Slice commit -- carries ONE @slice-01 .feature file (so P4 passes) and
    # the green contract test (so E2 alone would pass).
    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    (features / "slice_01.feature").write_text(_SLICE_FEATURE, encoding="utf-8")
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    # A LATER commit adds a SECOND @slice-01 .feature file -- present in the
    # working tree, never carried by the slice commit -> E1 SliceCommitIncomplete.
    (features / "slice_01_extra.feature").write_text(_SLICE_FEATURE, encoding="utf-8")
    _commit(repo, "test: add a second slice-01 .feature late\n")

    return repo, slice_sha


@pytest.fixture
def e2_failing_slice_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo with a valid slice but a RED contract test on HEAD.

    The slice commit ships its `@slice-01` `.feature` file (E1 passes), but a
    later commit adds a FAILING contract-marked test, so E2's whole-tree
    contract suite goes red on HEAD and exits non-zero.

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    (features / "slice_01.feature").write_text(_SLICE_FEATURE, encoding="utf-8")
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    # A later commit adds a RED contract test -- E2's suite goes red on HEAD.
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_RED, encoding="utf-8"
    )
    _commit(repo, "test: add a failing contract test after the slice commit\n")

    return repo, slice_sha


def test_e1_gate_fail_blocks_slice_and_appends_slice_commit_blocked(
    e1_failing_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criteria 1+2+3: E1 (completeness) failing blocks the slice, exit 1.

    The slice commit is missing its `.feature` file, so E1 exits non-zero.
    The gate-fail path appends a genuine `SliceCommitBlocked` ledger record,
    emits a `SliceReverifyBlocked` JSON event naming E1, exits 1, and appends
    NO `SliceReverified` provenance record.
    """
    repo, slice_sha = e1_failing_slice_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    # Criterion 2: the blocked event names the failing gate, exit 1.
    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyBlocked"
    assert payload["failing_gate"] == "check_slice_at_completeness"

    records_after = ledger.read_records()
    # Criterion 1: a genuine SliceCommitBlocked ledger record is appended.
    assert len(records_after) > records_before
    blocked = [r for r in records_after if r["event"] == "SliceCommitBlocked"]
    assert any(r["slice_id"] == "slice-01" for r in blocked)
    # Criterion 3: no provenance record on the blocked path.
    assert not [r for r in records_after if r["event"] == "SliceReverified"]
    assert "slice-01" not in ledger.verified_slices()


def test_e2_gate_fail_blocks_slice_and_appends_slice_commit_blocked(
    e2_failing_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criteria 1+2+3: E2 (contract gate) failing blocks the slice, exit 1.

    E1 passes (the `.feature` file is present) but a red contract test on HEAD
    makes E2 exit non-zero. The gate-fail path appends a genuine
    `SliceCommitBlocked` ledger record, emits a `SliceReverifyBlocked` event
    naming E2, exits 1, and appends NO `SliceReverified` provenance record.
    """
    repo, slice_sha = e2_failing_slice_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyBlocked"
    assert payload["failing_gate"] == "run_contract_gate"

    records_after = ledger.read_records()
    assert len(records_after) > records_before
    blocked = [r for r in records_after if r["event"] == "SliceCommitBlocked"]
    assert any(r["slice_id"] == "slice-01" for r in blocked)
    assert not [r for r in records_after if r["event"] == "SliceReverified"]
    assert "slice-01" not in ledger.verified_slices()


# --------------------------------------------------------------------------
# Step 01-05 -- Precondition P4: in-commit AT presence.
#
# P4 closes the vacuous-E1-pass on a slice whose `.feature` ATs were deleted
# AFTER the commit. E1 walks the *working tree*; a slice whose AT file once
# existed in the slice commit but was later removed from the tree would skip
# E1 entirely (no `.feature` found -> nothing reported missing) and emit a
# mechanically-truthful-but-semantically-false `SliceCommitVerified`. P4 runs
# in the precondition group (before any gate) and asserts the COMMIT TREE
# itself carries at least one `@slice-NN` `.feature` for `--slice-id`.
# --------------------------------------------------------------------------


@pytest.fixture
def at_deleted_after_commit_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo whose slice AT was deleted from the tree post-commit.

    History (oldest -> newest):
      1. base commit (pytest.ini).
      2. SLICE COMMIT -- carries the `@slice-01` `.feature` file + `Slice-Id`
         trailer.
      3. a LATER commit DELETES that `.feature` file from the working tree.

    The slice commit genuinely carried its AT, so E1 walking the working tree
    would now find no `@slice-01` `.feature` and report nothing missing -- a
    vacuous pass. P4, reading the COMMIT TREE, must still refuse, because the
    slice's ATs no longer live in the tree the reverify is run against.

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    feature_path = features / "slice_01.feature"
    feature_path.write_text(_SLICE_FEATURE, encoding="utf-8")
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    # A LATER commit deletes the slice's `.feature` file from the tree.
    feature_path.unlink()
    _commit(repo, "chore: drop the slice-01 .feature file\n")

    return repo, slice_sha


@pytest.fixture
def commit_without_at_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo whose slice commit never carried any `.feature` AT.

    The slice commit carries a `Slice-Id: slice-01` trailer (P2 passes) and is
    an ancestor of HEAD (P1 passes) but touches no `@slice-01` `.feature` file
    at all. P4 must refuse: zero in-commit ATs for the slice.

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    (repo / "placeholder.txt").write_text("no slice AT here\n", encoding="utf-8")
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    # A later commit keeps the slice commit off HEAD (P1 ancestor check).
    (repo / "later.txt").write_text("a later change\n", encoding="utf-8")
    _commit(repo, "chore: keep slice commit non-HEAD\n")

    return repo, slice_sha


def test_p4_refuses_slice_whose_at_was_deleted_after_the_commit(
    at_deleted_after_commit_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 2: an AT deleted post-commit emits `SliceReverifyRefused`.

    The slice's `@slice-01` `.feature` once lived in the slice commit but was
    later removed from the tree. E1 (working-tree walk) would now pass
    vacuously -- P4, reading the commit tree, refuses with exit 1 and appends
    NO ledger record (preconditions run before any gate).
    """
    repo, slice_sha = at_deleted_after_commit_repo

    # P4 reads the commit tree, so the working-tree-walk vacuous pass is moot;
    # the commit itself DID carry the AT here -- so P4 should actually PASS
    # for this fixture and the run proceeds. The genuine zero-in-commit refusal
    # is covered by `commit_without_at_repo` below.
    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    # The commit carried the AT -> P4 passes; the run proceeds past P4.
    # (It then runs the gates: E1 walks the working tree, finds no .feature,
    # reports nothing missing -> E1 passes; E2's green suite passes.)
    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"
    assert len(ledger.read_records()) > records_before


def test_p4_refuses_commit_carrying_zero_in_commit_slice_ats(
    commit_without_at_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 2: zero in-commit ATs -> `SliceReverifyRefused`, exit 1.

    The slice commit carries the trailer (P2 passes) and is an ancestor of
    HEAD (P1 passes) but no `@slice-01` `.feature` file at all. P4 refuses
    with exit 1 BEFORE any gate runs, and the refusal appends NO ledger
    record.
    """
    repo, slice_sha = commit_without_at_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyRefused"
    assert "slice-01" in payload["error"]

    # The refusal runs before any gate -> the ledger is untouched.
    assert len(ledger.read_records()) == records_before


def test_p4_passes_commit_carrying_its_slice_feature_at(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 3: a commit carrying its `.feature` AT passes P4.

    The `orphaned_green_slice_repo` slice commit ships its `@slice-01`
    `.feature` file. P4 finds it in the commit tree, the precondition group
    passes, and reverify proceeds to a `SliceReverified` success.
    """
    repo, slice_sha = orphaned_green_slice_repo

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"


# --------------------------------------------------------------------------
# Step 01-09 -- P4 existence probe must not crash on a path absent from the
# named commit's tree.
#
# `_in_commit_at_presence` iterates `files_in_commit(repo, commit)` -- the set
# of paths *touched* by the commit, which INCLUDES paths the commit DELETES
# (`git show --name-only` lists deletions). For a deleted-in-this-commit path,
# `git show {commit}:{path}` resolves nothing in the commit tree and `git`
# exits 128 -- the `check=True` `_git` helper then raises an uncaught
# `CalledProcessError` and the whole CLI crashes with a traceback.
#
# A `.feature` file absent from the named commit's tree is a normal
# NOT-IN-COMMIT result for P4, never an error. P4's contract is to evaluate
# whether the slice's `@slice-NN` `.feature` AT genuinely lives IN the commit;
# an absent file simply does not contribute -- the probe must skip it and
# continue, never raise.
# --------------------------------------------------------------------------


@pytest.fixture
def slice_commit_deletes_a_feature_file_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo whose slice commit DELETES a pre-existing `.feature` file.

    History (oldest -> newest):
      1. base commit (pytest.ini) AND a pre-existing `removed.feature` file.
      2. SLICE COMMIT -- DELETES `removed.feature`. `git show --name-only`
         lists the deleted path as touched by the commit, so
         `_in_commit_at_presence` iterates it and probes
         `{commit}:tests/acceptance/removed.feature` -- a path the commit tree
         no longer carries (the file was deleted there). `git show` exits 128
         and the `check=True` `_git` helper raises an uncaught
         `CalledProcessError`, crashing the CLI.
      3. a later commit grows the contract suite (so the slice commit is
         genuinely buried -- P5 passes).

    The commit tree carries a STRICT subset of the touched paths' content --
    the walking-skeleton-gate shape (commit `71716939c`) that crashes the CLI
    with `CalledProcessError` when P4's existence probe hits a deleted path.

    Returns ``(repo, slice_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # 1. base commit -- pytest.ini AND a pre-existing .feature file.
    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    removed_feature = features / "removed.feature"
    removed_feature.write_text(
        _SLICE_FEATURE.replace("@slice-01", "@slice-99"), encoding="utf-8"
    )
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    _commit(repo, "chore: base\n")

    # 2. the slice commit -- DELETES the pre-existing .feature file. The
    #    deleted path is the ONLY touched .feature, so the existence probe
    #    iterates it and `git show {commit}:removed.feature` exits 128.
    removed_feature.unlink()
    slice_sha = _commit(
        repo, "feat: walking skeleton slice-01 cleanup\n\nSlice-Id: slice-01\n"
    )

    # 3. a LATER commit grows the contract suite (P5 -- genuinely buried).
    (repo / "tests" / "test_more.py").write_text(
        _CONTRACT_TEST_GREEN.replace("test_slice_contract_holds", "test_more"),
        encoding="utf-8",
    )
    _commit(repo, "test: add another contract test after the slice commit\n")

    return repo, slice_sha


def test_p4_does_not_crash_when_commit_deletes_a_feature_file(
    slice_commit_deletes_a_feature_file_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 1+2: a `.feature` file absent from the commit tree is graceful.

    The slice commit DELETES `removed.feature` -- `git show --name-only` lists
    it as touched, so the P4 existence probe iterates it and probes
    `git show {commit}:removed.feature`, which resolves nothing in the commit
    tree. The probe must treat that absent path as not-in-commit -- skip it,
    continue -- never raise `CalledProcessError`.

    The commit carries no genuine `@slice-01` `.feature` AT in its tree, so
    P4 legitimately REFUSES (`SliceReverifyRefused`, exit 1) -- reaching a
    clean precondition verdict instead of crashing with a traceback.
    """
    repo, slice_sha = slice_commit_deletes_a_feature_file_repo

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyRefused"
    assert "slice-01" in payload["error"]


# --------------------------------------------------------------------------
# Step 01-06 -- Precondition P5: orphan-state.
#
# P5 confines reverify to a GENUINELY-ORPHANED (buried) slice -- a commit
# that is a STRICT ancestor of HEAD with at least one commit between it and
# HEAD. Without P5, reverify emits the identical `SliceCommitVerified` record
# the U2 G_COMMIT exit gate emits, callable at will even on a still-HEAD
# commit -- a routine-bypass vector (feature-delta sec.13 R-6, Residuality
# Pass S1 "reverify-as-bypass-vector"). P5 makes reverify and the U2 exit
# gate own DISJOINT mechanically-enforced domains: a still-HEAD slice is
# structurally unavailable to reverify. P5 runs in the precondition group,
# after P4, before any gate.
# --------------------------------------------------------------------------


@pytest.fixture
def slice_commit_is_head_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo whose slice commit IS HEAD (no commit buries it).

    History (oldest -> newest):
      1. base commit (pytest.ini).
      2. SLICE COMMIT -- carries the `@slice-01` `.feature` + `Slice-Id`
         trailer. This is HEAD: nothing is committed after it.

    The slice commit is an ancestor of HEAD only in the reflexive sense
    (it IS HEAD). P5 must refuse -- a still-HEAD slice is owned by the U2
    G_COMMIT exit gate, not reverify.

    Returns ``(repo, slice_commit_sha)`` where ``slice_commit_sha == HEAD``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    (features / "slice_01.feature").write_text(_SLICE_FEATURE, encoding="utf-8")
    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    slice_sha = _commit(repo, "feat: walking skeleton slice-01\n\nSlice-Id: slice-01\n")

    return repo, slice_sha


def test_p5_refuses_commit_equal_to_head(
    slice_commit_is_head_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 1: a commit equal to HEAD -> `SliceReverifyRefused`, exit 1.

    The slice commit IS HEAD -- no commit buries it. P5 refuses with exit 1
    BEFORE any gate runs (preconditions run before gates), so the refusal
    appends NO ledger record. This is the reverify-as-bypass-vector closure:
    a still-HEAD slice belongs to the U2 G_COMMIT exit gate.
    """
    repo, head_sha = slice_commit_is_head_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", head_sha))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyRefused"
    assert "slice-01" not in ledger.verified_slices()

    # The refusal runs before any gate -> the ledger is untouched.
    assert len(ledger.read_records()) == records_before


def test_p5_refuses_head_passed_literally(
    slice_commit_is_head_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 2: `--commit HEAD` (zero commits buried) -> refused, exit 1.

    Passing the literal ref `HEAD` resolves to the slice commit itself --
    `git rev-list HEAD..HEAD` is empty, zero commits bury it. P5 refuses
    regardless of whether the commit-ish is a SHA or the symbolic `HEAD`.
    """
    repo, _ = slice_commit_is_head_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-01", "HEAD"))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyRefused"
    assert len(ledger.read_records()) == records_before


def test_p5_passes_genuinely_buried_slice_commit(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 3: a genuinely-buried slice commit passes P5.

    In `orphaned_green_slice_repo` a later commit grows the contract suite
    AFTER the slice commit -- so the slice commit is a STRICT ancestor of
    HEAD with one commit between it and HEAD. P5 passes, the precondition
    group passes, and reverify proceeds to a `SliceReverified` success.
    """
    repo, slice_sha = orphaned_green_slice_repo

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"


# --------------------------------------------------------------------------
# Step 01-07 -- Precondition P6: predecessor-verified + SliceReverified
# provenance.
#
# P6 closes the carpaccio ordering hole: reverify of `slice-N` (N > 1) is
# refused when `slice-(N-1)` carries no `SliceCommitVerified` ledger record.
# Without P6 a reverify could mint an out-of-order `SliceCommitVerified`
# record, leaving a permanent M8-invisible hole (the U1 M8 carpaccio-order
# check keys on `SliceCommitVerified`). P6 mirrors the U1 M8 order check --
# immediate predecessor only, zero-padding-preserving -- and runs in the
# precondition group after P5, before any gate.
#
# The success path additionally appends an adjacent HMAC-chained
# `SliceReverified` provenance record (I-6): `verified_slices()` keys only
# on `SliceCommitVerified`, so the provenance record makes the recovery
# path auditable in the integrity log WITHOUT changing carpaccio ordering.
# --------------------------------------------------------------------------


@pytest.fixture
def slice_02_predecessor_unverified_repo(tmp_path: Path) -> tuple[Path, str]:
    """A temp-git repo with a buried `slice-02` whose `slice-01` is unverified.

    History (oldest -> newest):
      1. base commit (pytest.ini).
      2. SLICE-02 COMMIT -- carries the `@slice-02` `.feature` + `Slice-Id`
         trailer. This is the buried slice being reverified.
      3. a later commit grows the contract suite (so the slice-02 commit is
         genuinely buried -- P5 passes).

    The ledger carries NO `SliceCommitVerified` record for `slice-01`. P6
    must refuse: reverify of `slice-02` cannot precede its predecessor.

    Returns ``(repo, slice_02_commit_sha)``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    (repo / "pytest.ini").write_text(_TEMP_PYTEST_INI, encoding="utf-8")
    _commit(repo, "chore: base\n")

    features = repo / "tests" / "acceptance"
    features.mkdir(parents=True)
    (features / "slice_02.feature").write_text(
        _SLICE_FEATURE.replace("@slice-01", "@slice-02"), encoding="utf-8"
    )
    slice_sha = _commit(repo, "feat: walking skeleton slice-02\n\nSlice-Id: slice-02\n")

    (repo / "tests" / "test_contract.py").write_text(
        _CONTRACT_TEST_GREEN, encoding="utf-8"
    )
    _commit(repo, "test: add contract test after the slice commit\n")

    return repo, slice_sha


@pytest.fixture
def slice_02_predecessor_verified_repo(
    slice_02_predecessor_unverified_repo: tuple[Path, str],
) -> tuple[Path, str]:
    """The `slice-02` repo with `slice-01` already carrying a verified record.

    Built on `slice_02_predecessor_unverified_repo` by appending a genuine
    `SliceCommitVerified` ledger record for `slice-01`. P6 then finds the
    predecessor verified and the precondition group passes.

    Returns ``(repo, slice_02_commit_sha)``.
    """
    repo, slice_sha = slice_02_predecessor_unverified_repo
    AtCompletionLedger(_FEATURE_ID, repo).append_gate_event(
        event="SliceCommitVerified", slice_id="slice-01"
    )
    return repo, slice_sha


def test_p6_refuses_slice_02_when_predecessor_unverified(
    slice_02_predecessor_unverified_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 1: reverify of `slice-02` with an unverified `slice-01` refused.

    The ledger carries no `SliceCommitVerified` record for `slice-01`. P6
    refuses with exit 1 BEFORE any gate runs, and the refusal appends NO
    ledger record. This closes the out-of-order-mint hole: reverify cannot
    mint a `slice-02` record while `slice-01` is M8-invisible.
    """
    repo, slice_sha = slice_02_predecessor_unverified_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    records_before = len(ledger.read_records())

    exit_code = main(_argv(repo, "slice-02", slice_sha))

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverifyRefused"
    assert "slice-01" in payload["error"]

    # The refusal runs before any gate -> the ledger is untouched.
    assert len(ledger.read_records()) == records_before
    assert "slice-02" not in ledger.verified_slices()


def test_p6_passes_slice_01_vacuously(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 2: reverify of `slice-01` passes P6 vacuously.

    `slice-01` has no predecessor -- P6 is the base case and never refuses.
    The `orphaned_green_slice_repo` reverify of `slice-01` proceeds past the
    precondition group to a `SliceReverified` success.
    """
    repo, slice_sha = orphaned_green_slice_repo

    exit_code = main(_argv(repo, "slice-01", slice_sha))

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"


def test_p6_passes_slice_02_when_predecessor_verified(
    slice_02_predecessor_verified_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 1 (pass side): a verified `slice-01` lets `slice-02` proceed.

    With `slice-01` carrying a `SliceCommitVerified` record, P6 finds the
    predecessor verified, the precondition group passes, and reverify of
    `slice-02` proceeds to a `SliceReverified` success.
    """
    repo, slice_sha = slice_02_predecessor_verified_repo

    exit_code = main(_argv(repo, "slice-02", slice_sha))

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out.strip())
    assert payload["event"] == "SliceReverified"
    assert payload["slice_id"] == "slice-02"


def test_successful_reverify_appends_adjacent_slice_reverified_provenance(
    orphaned_green_slice_repo: tuple[Path, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion 3: a successful reverify appends a `SliceReverified` record.

    The success path appends TWO adjacent HMAC-chained ledger records: the
    `SliceCommitVerified` record (M8-visible) and a `SliceReverified`
    provenance record (I-6). `verified_slices()` keys only on
    `SliceCommitVerified`, so its shape is unchanged -- the provenance
    record makes the recovery path auditable without altering ordering.
    """
    repo, slice_sha = orphaned_green_slice_repo

    ledger = AtCompletionLedger(_FEATURE_ID, repo)
    verified_before = ledger.verified_slices()

    exit_code = main(_argv(repo, "slice-01", slice_sha))
    assert exit_code == 0
    capsys.readouterr()

    records_after = ledger.read_records()
    # A genuine SliceReverified provenance record is appended.
    provenance = [r for r in records_after if r["event"] == "SliceReverified"]
    assert any(r["slice_id"] == "slice-01" for r in provenance)
    # It is adjacent to the SliceCommitVerified record (the chain reads back
    # intact under M7 -- read_records would raise on a broken HMAC chain).
    verified_records = [r for r in records_after if r["event"] == "SliceCommitVerified"]
    assert verified_records
    verified_seq = max(r["seq"] for r in verified_records)
    provenance_seq = max(r["seq"] for r in provenance)
    assert provenance_seq == verified_seq + 1

    # verified_slices() shape is unchanged -- it keys only on
    # SliceCommitVerified, so the provenance record is M8-invisible.
    verified_after = ledger.verified_slices()
    assert verified_after == verified_before | {"slice-01"}
