"""Regression: a subsequent ensure_nwave_gitignore must not re-ignore the marker.

Defect (DELIVER verification, feature nwave-project-activation-gating): after
``nwave-ai project enable`` / auto-marking repairs the nested ``.nwave/.gitignore``
(adding ``!local-config.json`` so the activation marker ``.nwave/local-config.json`` is
trackable), the very next runtime path that lazily creates ``.nwave/`` content
calls ``ensure_nwave_gitignore`` — which unconditionally rewrote the nested
ignore to ``"{marker}\n*\n"``, clobbering the ``!local-config.json`` re-include and
re-hiding the marker from git.

The two nested-gitignore writers (``AutoMarkingService`` and
``ensure_nwave_gitignore``) must agree on ONE canonical content so they cannot
disagree. This drives the production fix through real ``git check-ignore``.
"""

from __future__ import annotations

import subprocess
from typing import TYPE_CHECKING

from des.adapters.driven.git.git_track_probe import is_tracked
from des.application.auto_marking_service import AutoMarkingService
from des.domain.nwave_dir_gitignore import ensure_nwave_gitignore


if TYPE_CHECKING:
    from pathlib import Path


_MARKER = "# Generated by nWave. Do not edit."


def _init_git_repo(project_root: Path) -> None:
    for argv in (
        ["git", "init", "--quiet"],
        ["git", "config", "user.email", "test@nwave.local"],
        ["git", "config", "user.name", "nWave Test"],
    ):
        subprocess.run(argv, cwd=project_root, check=True, capture_output=True)


def test_subsequent_ensure_preserves_marker_trackability(tmp_path: Path) -> None:
    """A later ensure_nwave_gitignore must not re-ignore the activation marker."""
    project_root = tmp_path / "project"
    nwave_dir = project_root / ".nwave"
    nwave_dir.mkdir(parents=True)
    _init_git_repo(project_root)

    # Shipped state: root ignores .nwave/, nested ignores everything.
    (project_root / ".gitignore").write_text(".nwave/\n", encoding="utf-8")
    (nwave_dir / ".gitignore").write_text(f"{_MARKER}\n*\n", encoding="utf-8")
    marker = nwave_dir / "local-config.json"
    marker.write_text('{"enabled_for_repo": true}\n', encoding="utf-8")

    # Activation repairs both gitignore layers -> marker becomes trackable.
    AutoMarkingService().fix_gitignore(project_root=project_root)
    assert is_tracked(project_root, marker), (
        "fix_gitignore should make marker trackable"
    )

    # A subsequent lazy .nwave/ write rewrites the nested .gitignore.
    ensure_nwave_gitignore(nwave_dir)

    # The marker MUST remain trackable — the re-include must survive.
    assert is_tracked(project_root, marker), (
        "ensure_nwave_gitignore clobbered the !local-config.json re-include — "
        "marker re-ignored after a subsequent .nwave/ write"
    )
    nested = (nwave_dir / ".gitignore").read_text(encoding="utf-8")
    assert _MARKER in nested, "banner must be preserved"
    assert "!local-config.json" in nested, "re-include must be preserved"


def test_ensure_nwave_gitignore_emits_reinclude_by_default(tmp_path: Path) -> None:
    """Fresh nested ignore created by ensure_nwave_gitignore keeps marker trackable."""
    project_root = tmp_path / "project"
    nwave_dir = project_root / ".nwave"
    nwave_dir.mkdir(parents=True)
    _init_git_repo(project_root)
    (project_root / ".gitignore").write_text(
        ".nwave/*\n!.nwave/local-config.json\n", encoding="utf-8"
    )

    # First runtime write under .nwave/ creates the nested ignore from scratch.
    ensure_nwave_gitignore(nwave_dir)

    marker = nwave_dir / "local-config.json"
    marker.write_text('{"enabled_for_repo": true}\n', encoding="utf-8")
    assert is_tracked(project_root, marker), (
        "nested ignore created by ensure_nwave_gitignore must not hide the marker"
    )
