[cosmic-ray]
module-path = "src/des/application/housekeeping_service.py"
timeout = 60.0
excluded-modules = []
test-command = "pytest -x tests/des/unit/application/test_housekeeping_service.py tests/des/unit/application/test_housekeeping_config.py tests/des/acceptance/test_housekeeping_acceptance.py"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.execution-engine]
name = "local"
