"""Shared helper to ensure .nwave/.gitignore exists.

Every runtime path that lazily creates content under .nwave/ must call
ensure_nwave_gitignore right after creating the directory and before writing
any file. This prevents accidental commits of generated nWave state when the
user has not yet seen the directory.

Behavior contract:
- Idempotent: safe to call repeatedly
- Walks UP from the input path to find the nearest .nwave/ ancestor (so callers
  can pass any descendant path, not just the .nwave/ root itself)
- Preserves user-customized .gitignore: if the file exists and does NOT contain
  the nWave generation marker, leaves it untouched
- Fail-silent on OSError (read-only directories, permission errors)
"""

from __future__ import annotations

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from pathlib import Path


_MARKER = "# Generated by nWave. Do not edit."
_CONTENT = f"{_MARKER}\n*\n"


def ensure_nwave_gitignore(path: Path) -> None:
    """Ensure a .gitignore exists in the .nwave/ ancestor of ``path``.

    Walks upward from ``path`` until a directory named ``.nwave`` is found,
    then creates ``.nwave/.gitignore`` with the standard nWave content. If no
    ``.nwave`` ancestor is found, the call is a no-op.

    Args:
        path: Any path inside (or equal to) a ``.nwave`` directory.
    """
    nwave_dir = _find_nwave_ancestor(path)
    if nwave_dir is None:
        return

    gitignore = nwave_dir / ".gitignore"
    try:
        if gitignore.exists():
            content = gitignore.read_text(encoding="utf-8")
            if _MARKER not in content:
                # User-customized — do not overwrite.
                return
        gitignore.write_text(_CONTENT, encoding="utf-8")
    except OSError:
        # Read-only directory or permission error — fail silent.
        pass


def _find_nwave_ancestor(path: Path) -> Path | None:
    """Return the nearest ``.nwave`` directory at or above ``path``."""
    current = path
    while current != current.parent:
        if current.name == ".nwave":
            return current
        current = current.parent
    return None
