"""Unit tests for the shared ensure_nwave_gitignore helper."""

from __future__ import annotations

import stat
import sys
from typing import TYPE_CHECKING

import pytest


if TYPE_CHECKING:
    from pathlib import Path

from des.domain.nwave_dir_gitignore import ensure_nwave_gitignore


_MARKER = "# Generated by nWave. Do not edit."


def test_creates_gitignore_when_absent(tmp_path: Path) -> None:
    nwave_dir = tmp_path / ".nwave"
    nwave_dir.mkdir()

    ensure_nwave_gitignore(nwave_dir)

    gitignore = nwave_dir / ".gitignore"
    assert gitignore.exists()
    content = gitignore.read_text(encoding="utf-8")
    assert _MARKER in content
    assert "*" in content


def test_idempotent_on_repeated_calls(tmp_path: Path) -> None:
    nwave_dir = tmp_path / ".nwave"
    nwave_dir.mkdir()

    ensure_nwave_gitignore(nwave_dir)
    first = (nwave_dir / ".gitignore").read_text(encoding="utf-8")
    ensure_nwave_gitignore(nwave_dir)
    second = (nwave_dir / ".gitignore").read_text(encoding="utf-8")

    assert first == second


def test_preserves_user_customized_gitignore(tmp_path: Path) -> None:
    nwave_dir = tmp_path / ".nwave"
    nwave_dir.mkdir()
    gitignore = nwave_dir / ".gitignore"
    user_content = "# my own rules\n!keep-me\n"
    gitignore.write_text(user_content, encoding="utf-8")

    ensure_nwave_gitignore(nwave_dir)

    assert gitignore.read_text(encoding="utf-8") == user_content


def test_walks_up_from_descendant_path(tmp_path: Path) -> None:
    nwave_dir = tmp_path / ".nwave"
    deep = nwave_dir / "des" / "logs"
    deep.mkdir(parents=True)

    ensure_nwave_gitignore(deep)

    assert (nwave_dir / ".gitignore").exists()


def test_noop_when_no_nwave_ancestor(tmp_path: Path) -> None:
    other = tmp_path / "not-nwave"
    other.mkdir()

    ensure_nwave_gitignore(other)

    assert not any(p.name == ".gitignore" for p in tmp_path.rglob(".gitignore"))


@pytest.mark.skipif(sys.platform.startswith("win"), reason="POSIX permission semantics")
def test_swallows_oserror_on_readonly_directory(tmp_path: Path) -> None:
    nwave_dir = tmp_path / ".nwave"
    nwave_dir.mkdir()
    # Make directory read+execute only (no write)
    nwave_dir.chmod(stat.S_IRUSR | stat.S_IXUSR)
    try:
        # Must not raise
        ensure_nwave_gitignore(nwave_dir)
    finally:
        nwave_dir.chmod(stat.S_IRWXU)
        # Cleanup any partial state
        for p in nwave_dir.iterdir():
            p.chmod(stat.S_IRWXU)
