"""verify_hooks — guarantee the project's git hooks are genuinely installed.

`pre-commit install --install-hooks --overwrite` (the `install-hooks` poe
task) writes `.git/hooks/<type>` for every type in
`default_install_hook_types`. What it CANNOT guarantee is that those hooks
are the ones git will actually run: a `core.hooksPath` override silently
redirects git away from `.git/hooks/`, so every hook in there is ignored and
none of our checks fire. This repo's own test suite is known to pollute the
shared `.git/config` (e.g. pointing `core.hooksPath` at `/dev/null` — see
the commit-author-identity research §2.7), which leaves a working tree where
`pre-commit install` reports success but no hook ever runs.

`verify-hooks` closes that gap. It FAILS LOUDLY (non-zero exit + actionable
message) unless the local git hooks are genuinely installed AND authoritative:

1. Reads the required hook types from `.pre-commit-config.yaml`
   (`default_install_hook_types` — the single source of truth). An absent
   or empty list is itself a failure (exit 2): nothing required means no
   hook is enforced. Unparseable YAML, or a non-list value, is likewise an
   environment/config error (exit 2), never a silent "0 hooks OK".
2. `core.hooksPath` guard: the config must be unset, or resolve to the
   repo's default hooks dir (`<git-common-dir>/hooks`). If it points
   elsewhere, FAIL — git ignores `.git/hooks/`. This guard reads all scopes
   (system/global/local), so a developer with a global hooks manager (e.g.
   husky or lefthook) configured at system/global scope will trigger this
   failure. That is correct and intentional: under any non-default
   `core.hooksPath`, git will not run `.git/hooks/`, so nWave's hooks are
   genuinely not active and must be reconciled with the system setup.
3. Per-type presence + ownership + liveness: each required hook file must
   exist, carry pre-commit's generated-file marker as a banner comment near
   the top (a buried/spoofed marker below a payload does NOT count), AND be
   executable — git silently skips a non-executable hook, so a
   marker-bearing but non-exec hook is installed-but-dead.

CLI contract:
- `python scripts/validation/verify_hooks.py [--repo-root <path>]`
- Exit 0 when hooks are installed and authoritative; prints an OK summary.
- Exit 1 on any problem; lists each problem with its fix.
- Exit 2 on usage / environment error (not a git repo, missing/empty/
  unparseable config, git unavailable).

Architecture (functional split, matching the `validate_*` neighbours):
- Pure core: `check_hooks(hook_types, hooks_dir, hooks_path_config, reader)`
  takes injected state and returns a list of `Problem`. No I/O.
- Thin wrappers: `read_required_hook_types(config_path)` parses the YAML;
  `git_default_hooks_dir` / `git_hooks_path_config` read real git state.
- CLI shell: `main(argv)` wires real state into the pure core, prints
  diagnostics, returns the exit code.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING, NamedTuple


if TYPE_CHECKING:
    from collections.abc import Callable


def _load_yaml():
    """Lazily import PyYAML.

    This script runs as a pre-commit `language: system` hook under a bare
    python3 with no venv — PyYAML is a venv-only dependency and must not be
    imported at module scope, or the hook crashes before it does any work.
    """
    try:
        import yaml
    except ModuleNotFoundError as exc:
        print(
            "ERROR: PyYAML unavailable under this interpreter; "
            "run via `uv run` or install pyyaml.",
            file=sys.stderr,
        )
        raise SystemExit(2) from exc
    return yaml


#: Marker pre-commit writes into every generated hook file. Its presence is
#: how we distinguish a pre-commit-managed hook from a foreign script.
PRECOMMIT_MARKER: str = "File generated by pre-commit"

#: The fix for a missing or foreign hook.
_INSTALL_FIX: str = "uv run poe install-hooks"

#: The fix for a hijacked core.hooksPath.
_HOOKSPATH_FIX: str = (
    "git config --unset-all core.hooksPath  (then: uv run poe install-hooks)"
)

#: Upper bound on any single git invocation, so a locked/hung git index cannot
#: hang the gate indefinitely.
_GIT_TIMEOUT_SECONDS: float = 10.0


class ConfigError(Exception):
    """`.pre-commit-config.yaml` is unparseable or structurally malformed."""


class GitError(Exception):
    """`git` could not be invoked (missing binary, timeout, or crash)."""


class Problem(NamedTuple):
    """A single reason the local hooks are not installed-and-authoritative."""

    kind: str  # "hooks_path_bypass" | "missing" | "foreign" | "not_executable"
    detail: str  # human-readable description of what is wrong
    fix: str  # the exact command that resolves it


# ---------------------------------------------------------------------------
# Pure core
# ---------------------------------------------------------------------------


def _has_banner_marker(content: str) -> bool:
    """True when the pre-commit marker sits as a banner comment near the top.

    `pre-commit install` writes the marker as a comment on line 2, directly
    under the shebang. A foreign script can *embed* the marker string lower
    down (in a buried comment, below its own payload) to spoof a bare
    substring check; requiring the marker in a leading comment line defeats
    that. We scan the first two lines — line 1 is the shebang, line 2 the
    genuine banner — and never deeper, so a payload-then-marker spoof fails.
    """
    for line in content.splitlines()[:2]:
        stripped = line.strip()
        if stripped.startswith("#") and PRECOMMIT_MARKER in stripped:
            return True
    return False


def check_hooks(
    hook_types: list[str],
    hooks_dir: Path,
    hooks_path_config: Path | None,
    marker_reader: Callable[[str], str | None],
    is_executable: Callable[[str], bool] | None = None,
) -> list[Problem]:
    """Verify hooks are installed and authoritative. Pure — no I/O.

    Args:
        hook_types: required hook type names (from `default_install_hook_types`).
        hooks_dir: the repo's default hooks dir, resolved
            (`<git-common-dir>/hooks`), immune to `core.hooksPath`.
        hooks_path_config: the resolved value of `core.hooksPath`, or `None`
            when the key is unset.
        marker_reader: given a hook-type name, returns the content of the
            corresponding hook file in `hooks_dir`, or `None` if absent.
        is_executable: optional predicate — given a hook-type name, returns
            whether that hook file carries the executable bit. `None` (the
            default) means "assume executable" and skips the check, so callers
            that inject only a `marker_reader` keep their behaviour. The real
            CLI wires a genuine `os.access(..., X_OK)` probe: git silently
            ignores a non-executable hook, so a marker-bearing but non-exec
            hook is installed-but-dead and must be flagged.

    Returns:
        A list of `Problem`. Empty list means the hooks are genuinely
        installed and authoritative.
    """
    # Guard first: if core.hooksPath redirects git away from the default
    # hooks dir, the per-type files are moot — git never runs them. Report
    # the bypass as the dominant (and only) problem so the message is clear.
    if hooks_path_config is not None and hooks_path_config != hooks_dir:
        return [
            Problem(
                kind="hooks_path_bypass",
                detail=(
                    f"core.hooksPath points at {hooks_path_config}, not the "
                    f"repo default {hooks_dir}; git ignores {hooks_dir} so no "
                    "hook fires"
                ),
                fix=_HOOKSPATH_FIX,
            )
        ]

    problems: list[Problem] = []
    for hook_type in hook_types:
        content = marker_reader(hook_type)
        if content is None:
            problems.append(
                Problem(
                    kind="missing",
                    detail=f"required hook '{hook_type}' is not installed in {hooks_dir}",
                    fix=_INSTALL_FIX,
                )
            )
            continue
        if not _has_banner_marker(content):
            problems.append(
                Problem(
                    kind="foreign",
                    detail=(
                        f"hook '{hook_type}' exists but is not pre-commit-managed "
                        "(missing the generated-file banner — foreign script)"
                    ),
                    fix=_INSTALL_FIX,
                )
            )
            continue
        if is_executable is not None and not is_executable(hook_type):
            problems.append(
                Problem(
                    kind="not_executable",
                    detail=(
                        f"hook '{hook_type}' exists but is not executable; git "
                        "ignores non-executable hooks, so it never runs"
                    ),
                    fix=_INSTALL_FIX,
                )
            )
    return problems


# ---------------------------------------------------------------------------
# Thin wrappers — config parsing + real git state
# ---------------------------------------------------------------------------


def read_required_hook_types(config_path: Path) -> list[str]:
    """Read `default_install_hook_types` from a `.pre-commit-config.yaml`.

    Returns an empty list when the key is absent — the caller decides whether
    "nothing declared" is acceptable (it is not, for this gate).

    Raises:
        ConfigError: when the YAML cannot be parsed, or when the key is
            present but is not a list of hook-type names (e.g. a scalar
            string or int). Both are environment/config errors, not "no
            problems found".
    """
    yaml = _load_yaml()
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise ConfigError(f"could not parse {config_path}: {exc}") from exc
    raw = data.get("default_install_hook_types")
    if raw is None:
        return []
    if not isinstance(raw, list):
        raise ConfigError(
            f"default_install_hook_types in {config_path} must be a list of "
            f"hook-type names, got {type(raw).__name__}"
        )
    return [str(t) for t in raw]


def _run_git(repo_root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    """Run a git command, mapping invocation failures to `GitError`.

    Catches `FileNotFoundError` (git not on PATH) and `subprocess.SubprocessError`
    (which includes `TimeoutExpired` for a locked/hung git) so the CLI shell can
    translate them into a clean exit-2 message instead of an uncaught traceback.
    """
    try:
        return subprocess.run(
            ["git", *args],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=_GIT_TIMEOUT_SECONDS,
        )
    except FileNotFoundError as exc:
        raise GitError("git executable not found on PATH") from exc
    except subprocess.SubprocessError as exc:
        raise GitError(f"git invocation failed: {exc}") from exc


def git_default_hooks_dir(repo_root: Path) -> Path | None:
    """Resolve the repo's *default* hooks dir, immune to `core.hooksPath`.

    Deliberately uses `git rev-parse --git-common-dir` + `/hooks` rather than
    `git rev-parse --git-path hooks`: the latter HONOURS `core.hooksPath`, so
    it returns the override (e.g. `/dev/null`) — the very value we need to
    detect a bypass against. `--git-common-dir` is stable under the override,
    giving the genuine `.git/hooks` location pre-commit installs into.

    Returns `None` when `repo_root` is not a git work tree.
    """
    result = _run_git(repo_root, "rev-parse", "--git-common-dir")
    if result.returncode != 0:
        return None
    return (repo_root / result.stdout.strip() / "hooks").resolve()


def git_hooks_path_config(repo_root: Path) -> Path | None:
    """Read `core.hooksPath`, resolved against `repo_root`. `None` if unset."""
    result = _run_git(repo_root, "config", "--get", "core.hooksPath")
    if result.returncode != 0:
        return None
    value = result.stdout.strip()
    if not value:
        return None
    return (repo_root / value).resolve()


# ---------------------------------------------------------------------------
# CLI shell
# ---------------------------------------------------------------------------


def _format_failure(problems: list[Problem]) -> str:
    lines = [
        f"verify-hooks FAILED: {len(problems)} problem(s) — git hooks are not "
        "installed-and-authoritative.",
        "",
    ]
    for problem in problems:
        lines.append(f"  [{problem.kind}] {problem.detail}")
        lines.append(f"    fix: {problem.fix}")
    return "\n".join(lines)


def _format_success(hook_types: list[str]) -> str:
    return (
        "verify-hooks OK: "
        f"{len(hook_types)} hook type(s) installed and pre-commit-managed, "
        "core.hooksPath authoritative — "
        f"[{', '.join(hook_types)}]"
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry: `verify_hooks.py [--repo-root <path>]`.

    Args:
        argv: optional argument list (defaults to `sys.argv[1:]`).

    Returns:
        0 when hooks are installed and authoritative, 1 on problems, 2 on a
        usage / environment error.
    """
    args = sys.argv[1:] if argv is None else argv
    repo_root = Path(__file__).resolve().parents[2]
    rest = list(args)
    if rest and rest[0] == "--repo-root":
        if len(rest) < 2:
            print("usage: verify_hooks.py [--repo-root <path>]", file=sys.stderr)
            return 2
        repo_root = Path(rest[1]).resolve()
        rest = rest[2:]
    if rest:
        print("usage: verify_hooks.py [--repo-root <path>]", file=sys.stderr)
        return 2

    config_path = repo_root / ".pre-commit-config.yaml"
    if not config_path.is_file():
        print(f"error: {config_path} not found", file=sys.stderr)
        return 2

    try:
        hook_types = read_required_hook_types(config_path)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if not hook_types:
        print(
            f"error: {config_path} declares no default_install_hook_types; "
            "with nothing required, no hook is enforced",
            file=sys.stderr,
        )
        return 2

    try:
        hooks_dir = git_default_hooks_dir(repo_root)
        hooks_path_config = git_hooks_path_config(repo_root)
    except GitError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if hooks_dir is None:
        print(f"error: {repo_root} is not a git work tree", file=sys.stderr)
        return 2

    def reader(hook_type: str) -> str | None:
        path = hooks_dir / hook_type
        if not path.is_file():
            return None
        return path.read_text(encoding="utf-8", errors="replace")

    def is_executable(hook_type: str) -> bool:
        return os.access(hooks_dir / hook_type, os.X_OK)

    problems = check_hooks(
        hook_types, hooks_dir, hooks_path_config, reader, is_executable
    )
    if not problems:
        print(_format_success(hook_types))
        return 0
    print(_format_failure(problems))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
